---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: document
  path: _data/announcementBar.yml
  label: Announcement Bar
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install config set path 'vendor/bundle'
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --trace --drafts --unpublished
    --future --port 8080 --host 0.0.0.0 -d _site
