---
label: Trainer
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: hero_video_portrait
  label: hero_video_portrait
- type: text
  name: hero_video_landscape
  label: hero_video_landscape
- type: text
  name: hero_video_title
  label: hero_video_title
- type: text
  name: hero_video_description
  label: hero_video_description
- type: file
  name: section_one_image
  label: section_one_image
- type: text
  name: section_one_title
  label: section_one_title
- type: textarea
  name: section_one_description
  label: section_one_description
- type: file
  name: section_two_left_image
  label: section_two_left_image
- type: file
  name: section_two_right_image
  label: section_two_right_image
- type: file
  name: section_two_bg_image
  label: section_two_bg_image
- type: text
  name: section_two_title
  label: section_two_title
- type: textarea
  name: section_two_description
  label: section_two_description
- type: file
  name: section_three_image
  label: section_three_image
- type: text
  name: section_three_title
  label: section_three_title
- type: text
  name: section_three_description
  label: section_three_description
- type: file
  name: section_four_image_one
  label: section_four_image_one
- type: file
  name: section_four_image_two
  label: section_four_image_two
- type: text
  name: section_four_title
  label: section_four_title
- type: text
  name: section_four_description
  label: section_four_description
- type: file
  name: section_five_image
  label: section_five_image
- type: text
  name: section_five_title
  label: section_five_title
- type: text
  name: section_five_description
  label: section_five_description
