---
label: Trainee
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  hidden: true
- name: hero_video_portrait
  type: file
  config:
    maxSize: 250
  label: Hero Video Portrait
  default: "/assets/images/hero_vid_portrait.mp4"
- name: hero_video_landscape
  type: file
  config:
    maxSize: 250
  label: Hero Video Landscape
  default: "/assets/images/hero_vid_landscape.mp4"
- type: text
  name: hero_video_title
  label: Hero Video Title
- type: text
  name: hero_video_description
  label: Hero Video Description
- type: text
  name: section_one_title
  label: Section One Title
- type: text
  name: section_one_description
  label: Section One Description
- type: text
  name: section_two_title
  label: Section Two Title
- type: textarea
  name: section_two_description
  label: Section Two Description
- type: text
  name: section_three_title
  label: Section Three Title
- type: text
  name: section_three_description
  label: Section Three Description
- type: file
  name: section_four_left_image
  label: section_four_left_image
- type: file
  name: section_four_right_image
  label: section_four_right_image
- type: text
  name: section_four_title
  label: Section Four Title
- type: textarea
  name: section_four_description
  label: Section Four Description
- type: text
  name: section_four_subtitle
  label: Section Four Subtitle
- type: file
  name: section_five_image
  label: Section_five _image
- type: text
  name: section_five_title
  label: Section Five_Title
- type: text
  name: section_five_description
  label: Section Five Description
- name: section_one_image
  type: file
  config:
    maxSize: 250
  label: Section One Image
  default: "/assets/images/trainee-1.png"
- name: section_two_image
  type: file
  config:
    maxSize: 250
  label: Section Two Image
  default: "/assets/images/watch-connect.png"
- name: section_three_image
  type: file
  config:
    maxSize: 250
  label: Section Three Image
  default: "/assets/images/traniee-view.png"
- name: section_three_bg_image
  type: file
  config:
    maxSize: 250
  label: Section Three Bg Image
  default: "/assets/images/bg-blue-img.png"
